### ISSUE TITLE
Product attribute stability in order creation

### ISSUE THREAD

**Issue by Vincent-Profileo** [shoppingflux/shoppingfluxexport#119]
## Expected behaviour
If an incoherence is present on catalog (in product_attribute there is a value with id_product = 0) it should not create problems on order creation

## Actual behaviour
It does not create the order

## Steps to reproduce the behaviour
For a given product attribute, add a copy of this entry in database and put this new line to id_product=0

**Comment by MathieuSF** [comment]
We have a new case wit this error (see attached file).

The seller has managed this error with his technical team, and they said, it comes from the frais de gestion product, created by the module.

It seems the module is harcd-coded only for the first store, so we will have issus for multi-store configuration.
The product needs to be available for every store.
