### ISSUE TITLE
Get discount dates from the future

### ISSUE THREAD

**Issue by Vincent-Profileo** [shoppingflux/shoppingfluxexport#14]
## Expected behaviour

The flux must give the specific price in the future
## Actual behaviour

Specific prices comes only with the current applicable
## Steps to reproduce the behaviour

Generate the flux adding &discount=1 to the URL

**Comment by pgrimaud** [comment]
Hello, `&discount=1` seems much appropriated as parameter name.

**Comment by ronan-gloo** [comment]
fixed by #16
