### ISSUE TITLE
Integration of mondial relay delivery point ID

### ISSUE THREAD

**Issue by Vincent-Profileo** [shoppingflux/shoppingfluxexport#181]
## Expected behaviour
Should automatically set the delivery point ID
It should be activated with a checkbox in back office

## Actual behaviour
Not implemented yet

## Steps to reproduce the behaviour
Not implemented yet

**Comment by MathieuSF** [comment]
This field on Prestashop, fill with the delivery point ID, is used by all of the Shipping method module ?
It will works with Mondial Relay, Colissimo, etc ?

**Comment by clement-hollander** [comment]
@Vincent-Coll il y a 2 PR avec du code similaire, normal ?

**Comment by Vincent-Profileo** [comment]
@clement-hollander 
j'ai trouvé ceci :
https://github.com/shoppingflux/shoppingfluxexport/pull/196

Quelle est la 2ème stp ?
Merci d'avance

**Comment by clement-hollander** [comment]
@Vincent-Coll je n'ai rien dit, mais dans la PR il y a un conflit

**Comment by MathieuSF** [comment]
@Vincent-Coll 
Un marchand qui a mis en place la config des relay pour Cdiscount, nous fait le retour suivant sur le module et des soucis de celui-ci pour cette config.

Est-ce que ces retours sont bien corrigés par la version 4.4.0 ?

* Problème de la variable id_order
* Non reconnaissance de la ShippingMethod « REL » utilisé sur Cdiscount
* Forçage des Id relay sur 6 chiffres (bourrage de 0 à gauche) sinon le webservice d'étiquetage de MondialRelay ne fonctionne pas.

(en PJ, son module modifié)
[shoppingfluxexport (1).zip](https://github.com/shoppingflux/shoppingfluxexport/files/1087671/shoppingfluxexport.1.zip)

merci

**Comment by Vincent-Profileo** [comment]
@MathieuSF 
Le lien pour récupérer le ZIP ne fonctionne pas.
Je vous laisse m'envoyer cela sur un ticket ou par mail.
Merci d'avance
