### ISSUE TITLE
Only send the real weight of variants

### ISSUE THREAD

**Issue by ronan-gloo** [shoppingflux/shoppingfluxexport#20]
## Actual behaviour

In the feed, the `weight` property contains the difference between product weight and variant weight.
An other property, `total_weigh` provides the real variant weight.
## Expected behaviour

The `weight` MUST contains the REAL variant weight.
## BC break
- The weight value is different, and the information send to marketplaces also.

**Comment by Vincent-Profileo** [comment]
Hello,
Currently we have :
$combinations[$combinaison['id_product_attribute']]['poids'] = $combinaison['weight'] + $product->weight;
            $combinations[$combinaison['id_product_attribute']]['weight'] = $combinaison['weight'];


We should :
1) remove the tag "poids"
2) let "weight" be only the variant weight
3) add a new tag "total_weight"

Correct?

**Comment by clement-hollander** [comment]
No, there should be only one <weight> with for parent the weight of parent and for each variant the real size of the variant

**Comment by clement-hollander** [comment]
@Vincent-Coll This is not working : https://github.com/shoppingflux/shoppingfluxexport/blob/4.2.0/shoppingfluxexport.php#L1272
You call poids but above is weight

Moreover, the parent has a field 'poids' but 'weight' on the children, this should be the same across parent and child

**Comment by Vincent-Profileo** [comment]
@clement-hollander 
Ok, we made adjustement, tell us if it is what your are looking for?
Regards

**Comment by clement-hollander** [comment]
@Vincent-Coll thanks this is now OK
