### ISSUE TITLE
original_product_price dans table order_detail

### ISSUE THREAD

**Issue by MathieuSF** [shoppingflux/shoppingfluxexport#223]
Le CTO d'un marchand remonte l'info suivante, par rapport aux données à insérer dans la BDD lors d'un import commande.
Je vous laisse confirmer si ça vous parait logique. (comme il y a des modifs de prix par rapport à ce qui est publié sur les places de marché, je ne suis pas sûr de ce process).

## Expected behaviour

La valeur "product_price" ne devrait pas être égale à la valeur de "unit_price_tax_excl", elle devrait être égale à "original_product_price", ce qui permet aux autres logiciels de calculer correctement la remise (ou la plus value) appliquées sur le prix du produit.

## Actual behaviour

Dans la donnée "product_price", pour le moment, c'est la valeur "unit_price_tax_excl" qui est envoyée.

**Comment by Vincent-Profileo** [comment]
Bonjour,
Oui cette colonne est dans la table à titre indicatif et n'est pas utilisée directement par Prestashop. On peux donc modifier cette colonne sans impact fonctionnel et ce qui est proposé est cohérent.
Nous prévoyons donc l'implémentation.
Cordialement
