### ISSUE TITLE
_updatePrices function has an incorrect query

### ISSUE THREAD

**Issue by gregoryBonnardel** [shoppingflux/shoppingfluxexport#24]
## Expected behaviour

in _updatePrices it should update real prices and fees of an order
## Actual behaviour

It seems that fees will be forced to be associated to product_id 55

See https://github.com/shoppingflux/shoppingfluxexport/blob/dev/shoppingfluxexport.php#L1664

**Comment by flebap** [comment]
Fix done, thank you for the issue.
