### ISSUE TITLE
Log rotation broken

### ISSUE THREAD

**Issue by ghost** [shoppingflux/shoppingfluxexport#271]
## Expected behaviour

Log files should be rotating avec 24h

## Actual behaviour

The log files are no longer rotating. Probably an issue with function `rotateLogFile()`

## Steps to reproduce the behaviour

Call `log()` function to add a new log message after 24 hours.

**Comment by Vincent-Profileo** [comment]
Will be solved by
https://github.com/shoppingflux/shoppingfluxexport/issues/272
