### ISSUE TITLE
Duplicate code for SoFlexibilite in hookbackOfficeTop

### ISSUE THREAD

**Issue by Vincent-Profileo** [shoppingflux/shoppingfluxexport#282]
## Expected behaviour
No duplicate code for SoFlexibilite in hookbackOfficeTop

## Actual behaviour
Duplicate code for SoFlexibilite in hookbackOfficeTop

## Steps to reproduce the behaviour
Check the code, there is duplicate

**Comment by infiniweb** [comment]
@clement-hollander this one is safe to be merged
