### ISSUE TITLE
Adding a new field type in the feed to describe the product hierarchy

### ISSUE THREAD

**Issue by ghost** [shoppingflux/shoppingfluxexport#387]
## Expected behaviour

In a structural level, a product object might be:
- A product with combinations
- A product without combination
- A combination

## Actual behaviour

There is currently no fields in the feed that allows us to know in which condition we are.
For example we don't know for a specific produit in the feed if it's a combination, a product with/without combination.

The only way currently to know that is to look at the struction to see if `<combination>` is defined.

The goal here is therefore to add a new field for each product to identify this status.

**Comment by ghost** [comment]
Need to be discussed to know where this field should be added (can be in the features (for products) and attributs (for combination)) in order to appear in Shopping Feed.

**Comment by ghost** [comment]
We will add this field in attributes and caracteristiques

**Comment by MathieuSF** [comment]
Field are these one : 
parent or simple product : "caracteristiques"
child : "attributs"

And the texte in this field could be
```
<caracteristiques>
     <hierararchy>simple</hierararchy>
</caracteristiques>
OU
<caracteristiques>
     <hierararchy>parent</hierararchy>
</caracteristiques>
```
ET
```
<attributs>
     <hierararchy>child</hierararchy>
</attributs>
```
