### ISSUE TITLE
wholesale_price is missing in feed for combinations

### ISSUE THREAD

**Issue by ghost** [shoppingflux/shoppingfluxexport#388]
## Expected behaviour

`wholesale_price` should be visible for the "parent" product and its combinations.

## Actual behaviour

`wholesale_price` isn't visible in combinations.

## Steps to reproduce the behaviour

Generate the feed for a product with combinations and look for `wholesale_price`

**Comment by ghost** [comment]
To be discussed as we need to know at which level we need to add `wholesale_price` (in attributs or at root level?).

**Comment by infiniweb** [comment]
We will add this field in attributes and caracteristiques

**Comment by ghost** [comment]
@MathieuSF can you please check if this field `wholesale_price` is supported in the root feed of the product

**Comment by MathieuSF** [comment]
@infiniweb 
For simple/parent product, the wholesale_price field could be on the root level. (it's already what we have)
For child, it must be in the `<attributs>` field.
