### ISSUE TITLE
Stock management for Marketplace Expedited orders

### ISSUE THREAD

**Issue by MathieuSF** [shoppingflux/shoppingfluxexport#44]
## Expected behaviour

When we will import an order which is expedited by the marketplace (Amazon AFN for exemple), the stock won't be updated.
Stock for these orders are managed by marketplace, so if the order is imported on Prestashop, the stock needs to stay identical.
## Actual behaviour

When an expedited orders is imported on Prestashop, the stock is updated. 
Stock is decreasing from the product quantity.

**Comment by MathieuSF** [comment]
In addition, it should be a good idea to allow the seller to associate a specific status to these orders in the module configuration (with a selection list for exemple).

**Comment by ghost** [comment]
**todo**:

1. Translation of new configuration option in BO
2. Style of new configuration option (text too long creating display issue)
3. List of all marketplaces that have this feature (@MathieuSF @clement-hollander )
4. Update script required for `SHOPPING_FLUX_STATE_MP_EXP` in order to set by default `PS_OS_SHIPPING`

**Comment by MathieuSF** [comment]
3. Here, it's the list : Amazon, Cdiscount, ManoMano (monechelle), Priceminister

**Comment by ghost** [comment]
@MathieuSF please let me know the list of carrier for Cdiscount, ManoMano (monechelle), Priceminister

**Comment by MathieuSF** [comment]
@infiniweb 
On retrouve ces infos dans le champ du WS : "Marketplace"
Voici la liste : Amazon = AFN
Cdiscount = CLogistique
ManoMano = EPMM
priceminister : inusité (on n'intègre pas)

**Comment by ghost** [comment]
@MathieuSF pour AFN on utilisait jusqu'à présent `amazon fba`. C'était le nom de la place de marché. Par contre je n'ai pas le souvenir d'avoir vu `AFN`. Peux tu vérifier ?

**Comment by MathieuSF** [comment]
@infiniweb ok, c'est bon, j'ai eu les infos.
Donc en effet, pour Amazon, on renomme le truc.
Marketplace | Final name    |
|  Amazon      |  Amazon FBA   |
| Monechelle   | EPMM          |
| CDiscount    | CLogistique   |

Avec ça, on est bon.
