### ISSUE TITLE
Manage multiple token in the module

### ISSUE THREAD

**Issue by MathieuSF** [shoppingflux/shoppingfluxexport#46]
## Actual behaviour

For now, there is a token by store on prestashop.
If the merchant wants to manage more than 1 country, he needs to have more than 1 store on Prestashop.
But on prestashop, the seller can manage different languages and currency from an unique store.
it creates conflict to import orders from SF to Presta
## Expected behaviour

If the seller have multiple language/currency on his prestashop store, we should be able to manage a token from each combination, in order to create an account for each combination on SF and be able to manage correctly orders.
## Steps to reproduce the behaviour

Fill it :)

**Comment by Vincent-Profileo** [comment]
Hello,
There is also customers that have multi shop and like tohave one single token.
Can we imagine a configuration that would be accessible only by adding a parameter to URL and would be:

Shop group 1
       - shop 1
              - currency 1 / language 1 : TOKEN
              - currency 1 / language 2 : TOKEN
              - currency 2 / language 1 : TOKEN
              - currency 2 / language 2 : TOKEN
       - shop 2
              - currency 1 / language 1 : TOKEN
              - currency 1 / language 2 : TOKEN
              - currency 2 / language 1 : TOKEN
              - currency 2 / language 2 : TOKEN
       - shop 3
              etc etc....
Shop group 1
       - shop 1
              etc etc....

So we can manualy set the token. But by default the behaviour would remain the same.
Would it be ok?

**Comment by clement-hollander** [comment]
Hi,

For the principle I'm ok.

Instead of adding a parameter on the url, I'd prefer a section in the module configuration with all possibilities

Context : shop 1
- List of all possible configuration based on currencies and languages available for the shop 1

Context : shop 2 
- List of all possible configuration based on currencies and languages available for the shop 2

By default, we keep default language and currency when creating the account

**Comment by MathieuSF** [comment]
We have an issue on this configuration on 4.4.0

If we check the box for multitoken mode, each store has the same token (see attached file).
![multitoken_presta](https://user-images.githubusercontent.com/19793815/28832028-b047ec30-76db-11e7-91f3-9eb6bebaf1c1.PNG)

Each store needs to have an unique token to connect to Shopping Feed.
This unique token allows us to create an account and if the token is unknow.
This is important for managing orders on each store.

**Comment by Vincent-Profileo** [comment]
Ok, but did you try to set different tokens ? It does not save ?
Regards

**Comment by clement-hollander** [comment]
@MathieuSF Mathieu is right to avoid collisions, token must not be editable by the clients and generated at the install

**Comment by Vincent-Profileo** [comment]
@clement-hollander 
@MathieuSF 
I created https://github.com/shoppingflux/shoppingfluxexport/issues/257
Can we close this issue ?
Thank you
