### ISSUE TITLE
Allow to export SmartPrice's combination prices on subscribed channels

### ISSUE THREAD

**Issue by NicolasMugnier** [shoppingflux/shoppingfluxexport#49]
## Expected behaviour

SmartPrice for Prestashop is a BoostMyShop extension that allow to save different prices for each combination on different channels in a specific table. The goal will be to include these prices in shoppingfluxexport's feed in order to be able to set a specific price for each combination on each subscribed channels.
## Actual behaviour

Saved prices are not exported in shoppingfluxexport's xml file.

**Comment by ghost** [comment]
@MathieuSF do you avec marchant tickets concerning BoostMyShop

**Comment by MathieuSF** [comment]
@infiniweb 
Actually, Boostmyshop has found a way to get our feed and adapt it to integrate new prices fields.
This process is OK and next step is to manage this data throug API, so this issue could be closed.
