### ISSUE TITLE
Cdiscount fees

### ISSUE THREAD

**Issue by clement-hollander** [shoppingflux/shoppingfluxexport#62]

**Comment by clement-hollander** [comment]
@Vincent-Coll en réinitialisant le module, le produit FDG a été recrée, il faut vérifier s'il n'existe pas.
De plus il faudrait l'appeler shoppingfeed_fdg car fdg on a une chance que ça existe côté client

De plus meme si le produit passe si hors stock, il faut que le stock par défaut soit 999 (ou le maximum possible) car sinon on se prend un statut "en attente de réaprovisionnement"

**Comment by clement-hollander** [comment]
@Vincent-Coll toujours KO pour celui ci, le produit se recrée si module réinitialisé, et toujours stock à 0

![capture d ecran 2017-01-10 a 12 31 08](https://cloud.githubusercontent.com/assets/1830906/21804732/ce6644dc-d730-11e6-882d-a40926e5ec63.png)

**Comment by Vincent-Profileo** [comment]
@clement-hollander 

Nous avons fait un test :
Nous avons installé le module en local et le produit CDiscount fees - ShoppingFlux (id: 31) a bien été créé.

Nous avons ensuite lancé la réinitialisation du module et nous n'avons pas eu de création de nouveau produit CDiscount fees - ShoppingFlux : le produit a toujours l'id 31.

Nous avons aussi fait un désinstallation et réinstallation du module. Le produit CDiscount fees - ShoppingFlux est toujours présent et bien à l'id 31

De notre côté tout semble bon.

Nous faisons qqch différement?


Pour le stock c'est normal, il est en "autoriser les commandes hors stock"
