### ISSUE TITLE
Clean function should be improved

### ISSUE THREAD

**Issue by clement-hollander** [shoppingflux/shoppingfluxexport#63]
https://github.com/PrestaShop/shoppingfluxexport/blob/master/shoppingfluxexport.php#L1513

If a user has cara1, cara2, cara3, we'll retrieve cara.

but we can't replace easily this function, as it'll also change mapped fields on autotag

**Comment by Vincent-Profileo** [comment]
Hello,
Sorry I did not understood all. We have to change the regex in order to allow digit and letters, correct ?
Can we remove _clean function and only use clean ?
Thank you

**Comment by clement-hollander** [comment]
I think we temporarely need both, one with clean and one with _clean, otherwise all fields already used today will changed.

So if a user has cara1, we need to see both cara and cara1 at the moment

Later we'll remove _clean

**Comment by Vincent-Profileo** [comment]
@clement-hollander 
Sorry Clément I still have doubts.
In function clean I should remove the digits, correct ?

**Comment by clement-hollander** [comment]
We should 
1. keep what we do now, for retro compatibility
2. add a new clean function, that allow digits (and everything else accepted in a xml tag name)

For a user that has the cara1 characteristic, we should see
<caracteristiques><cara>A</cara><cara1>A</cara1></caracteristiques>
