### ISSUE TITLE
Unregister hook backOfficeTop

### ISSUE THREAD

**Issue by clement-hollander** [shoppingflux/shoppingfluxexport#64]
Use a migration to unregister hook backofficetop, but keep function for cron

**Comment by Vincent-Profileo** [comment]
Hello,
If we put it on CRON, the orders would be retrieved only when the CRON is called. The order won't be get enough often.
What about old feed.php behaviour?

**Comment by clement-hollander** [comment]
@Vincent-Coll This was to avoid this issue : https://github.com/shoppingflux/shoppingfluxexport/issues/84

But if your other PR fixed #84, I close this one for now
