### ISSUE TITLE
 requêtes SQL

### ISSUE THREAD

**Issue by bensundayevenning** [shoppingflux/shoppingfluxexport#66]
Remonté sur addons Prestashop par un anonymous :

PHP Errors :
Vous avez des erreurs de sécurité. Merci de vérifier toutes vos requêtes SQL et de bien caster vos variables dedans (pSQL, int...)

Ex:

WHERE id_product ='.$ids[0].' AND id_shop = '.$id_shop);

**Comment by clement-hollander** [comment]
@bensundayevenning Bonjour, où avez vous trouvé ce code ? Sur notre repo c'est bien casté : https://github.com/shoppingflux/shoppingfluxexport/blob/dev/shoppingfluxexport.php
