### ISSUE TITLE
Error remonté sur Presta Addons

### ISSUE THREAD

**Issue by bensundayevenning** [shoppingflux/shoppingfluxexport#67]
PHP Errors :
Le répertoire backward_compatibility est vide, cela va poser problème sur de nombreuses boutiques.

**Comment by clement-hollander** [comment]
@bensundayevenning bonjour, comment a été installé le module? il s'agit d'un submodule, qui référence le repo de Prestashop : https://github.com/PrestaShop/PrestaShop-backward_compatibility/tree/35e345cb573926c15094ba742039827a55d39de3 donc il ne devrait pas être vide
