### ISSUE TITLE
Simultaneous accesses can create 2 orders

### ISSUE THREAD

**Issue by Vincent-Profileo** [shoppingflux/shoppingfluxexport#84]
## Expected behaviour
If they are many employees accessing the back office, it should not create 2 times the orders

## Actual behaviour
It can create 2 orders

## Steps to reproduce the behaviour
Access with may employees while order creation : it will create sometimes orders 2 times

**Comment by clement-hollander** [comment]
This has not been asked for 4.2.0, please only make PR on 4.2.0 milestone

**Comment by clement-hollander** [comment]
@Vincent-Coll this is not working, you call a config https://github.com/shoppingflux/shoppingfluxexport/blob/dev/shoppingfluxexport.php#L1415 that is never set later

**Comment by clement-hollander** [comment]
👍  thanks
