### ISSUE TITLE
Error on order creation if name or firstname contains numbers

### ISSUE THREAD

**Issue by Vincent-Profileo** [shoppingflux/shoppingfluxexport#89]
## Expected behaviour
Firstname or name containing numbers should not crash order creation

## Actual behaviour
It does not create the order 

## Steps to reproduce the behaviour
Make on order creation with a name or firstname containing numbers

**Comment by clement-hollander** [comment]
@Vincent-Coll are your sure ? this regex replace all digits : https://github.com/shoppingflux/shoppingfluxexport/blob/dev/shoppingfluxexport.php#L1824

**Comment by Vincent-Profileo** [comment]
@clement-hollander 
Hello,
You are telling me that this regex replace all digits, and this is what we are looking for, as Prestashop does not allow digits in firstname and name.
What is the matter?

**Comment by Vincent-Profileo** [comment]
@clement-hollander 
I checked the history :  there was no commit on this issue an the code is good on customer and address creation.
I think we can close this issue
